import pandas as pd
from matplotlib import pyplot as plt

dfltt = pd.read_csv("SimResults/LTT.csv", sep="\s+")
dfpanels = pd.read_csv("SimResults/Panels.csv", sep="\s+")
dfVLM1 = pd.read_csv("SimResults/VLM1.csv", sep="\s+")
dfVLM2 = pd.read_csv("SimResults/VLM2.csv", sep="\s+")

fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(20, 12))
plt.tight_layout(pad=5)
plt.suptitle(f'2D Performance Plots', size=15)

axes[0, 0].plot(dfltt['alpha'], dfltt['CL'], label="LTT", marker='.', color='blue')
axes[0, 0].plot(dfpanels['alpha'], dfpanels['CL'], label="Panels", marker='.', color='red')
axes[0, 0].plot(dfVLM1['alpha'], dfVLM1['CL'], label="VLM1", marker='.', color='green')
axes[0, 0].plot(dfVLM2['alpha'], dfVLM2['CL'], label="VLM2", marker='.', color='yellow')
axes[0, 0].set_xlabel('Alpha [°]')
axes[0, 0].set_ylabel('CL [-]')
axes[0, 0].set_title('Lift Slope')
axes[0, 0].axhline(y=0, color='k')
axes[0, 0].axvline(x=0, color='k')
axes[0, 0].legend()
axes[0, 0].grid()

axes[0, 1].plot(dfltt['alpha'], dfltt['CD'], label="LTT", marker='.', color='blue')
axes[0, 1].plot(dfpanels['alpha'], dfpanels['CD'], label="Panels", marker='.', color='red')
axes[0, 1].plot(dfVLM1['alpha'], dfVLM1['CD'], label="VLM1", marker='.', color='green')
axes[0, 1].plot(dfVLM2['alpha'], dfVLM2['CD'], label="VLM2", marker='.', color='yellow')
axes[0, 1].set_xlabel('Alpha [°]')
axes[0, 1].set_ylabel('CD [-]')
axes[0, 1].set_title('Drag Slope')
axes[0, 1].axhline(y=0, color='k')
axes[0, 1].axvline(x=0, color='k')
axes[0, 1].legend()
axes[0, 1].grid()

axes[0, 2].plot(dfltt['CD'], dfltt['CL'], label="LTT", marker='.', color='blue')
axes[0, 2].plot(dfpanels['CD'], dfpanels['CL'], label="Panels", marker='.', color='red')
axes[0, 2].plot(dfVLM1['CD'], dfVLM1['CL'], label="VLM1", marker='.', color='green')
axes[0, 2].plot(dfVLM2['CD'], dfVLM2['CL'], label="VLM2", marker='.', color='yellow')
axes[0, 2].set_xlabel('Alpha [°]')
axes[0, 2].set_ylabel('CL [-]')
axes[0, 2].set_title('Lift Slope')
axes[0, 2].axhline(y=0, color='k')
axes[0, 2].axvline(x=0, color='k')
axes[0, 2].legend()
axes[0, 2].grid()

plt.show()