from dataframes import dfltt, dfpanels, dfvlm1 , dfvlm2, df3d
import pandas as pd
from matplotlib import pyplot as plt


fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(20, 12))
plt.tight_layout(pad=5)
plt.suptitle(f'XFLR5 vs Windtunnel', size=15)

axes[0, 0].plot(dfltt['alpha'], dfltt['CL'], label="LTT", marker='.', color='blue')
axes[0, 0].plot(dfpanels['alpha'], dfpanels['CL'], label="Panels", marker='.', color='red')
axes[0, 0].plot(dfvlm2['alpha'], dfvlm2['CL'], label="VLM2", marker='.', color='yellow')
axes[0, 0].plot(df3d['Alpha'][:33], df3d['CL'][:33], label="Windtunnel", marker='.', color='green')
axes[0, 0].set_xlabel('Alpha [°]')
axes[0, 0].set_ylabel('CL [-]')
axes[0, 0].set_title('Lift Slope')
axes[0, 0].axhline(y=0, color='k')
axes[0, 0].axvline(x=0, color='k')
axes[0, 0].legend()
axes[0, 0].grid()

axes[0, 1].plot(dfltt['alpha'], dfltt['CD'], label="LTT", marker='.', color='blue')
axes[0, 1].plot(dfpanels['alpha'], dfpanels['CD'], label="Panels", marker='.', color='red')
axes[0, 1].plot(dfvlm2['alpha'], dfvlm2['CD'], label="VLM2", marker='.', color='yellow')
axes[0, 1].plot(df3d['Alpha'][:33], df3d['CD'][:33], label="Windtunnel", marker='.', color='green')
axes[0, 1].set_xlabel('Alpha [°]')
axes[0, 1].set_ylabel('CD [-]')
axes[0, 1].set_title('Drag Slope')
axes[0, 1].axhline(y=0, color='k')
axes[0, 1].axvline(x=0, color='k')
axes[0, 1].legend()
axes[0, 1].grid()

axes[0, 2].plot(dfltt['CD'], dfltt['CL'], label="LTT", marker='.', color='blue')
axes[0, 2].plot(dfpanels['CD'], dfpanels['CL'], label="Panels", marker='.', color='red')
axes[0, 2].plot(dfvlm2['CD'], dfvlm2['CL'], label="VLM2", marker='.', color='yellow')
axes[0, 2].plot(df3d['CD'][:33], df3d['CL'][:33], label="Windtunnel", marker='.', color='green')
axes[0, 2].set_xlabel('CD [°]')
axes[0, 2].set_ylabel('CL [-]')
axes[0, 2].set_title('Drag Bucket')
axes[0, 2].axhline(y=0, color='k')
axes[0, 2].axvline(x=0, color='k')
axes[0, 2].legend()
axes[0, 2].grid()


axes[1, 0].plot(dfltt['alpha'], dfltt['Cm'], label="LTT", marker='.', color='blue')
axes[1, 0].plot(dfpanels['alpha'], dfpanels['Cm'], label="Panels", marker='.', color='red')
axes[1, 0].plot(dfvlm2['alpha'], dfvlm2['Cm'], label="VLM2", marker='.', color='yellow')
axes[1, 0].plot(df3d['Alpha'][:33], df3d['Cm_pitch'][:33], label="Windtunnel", marker='.', color='green')
axes[1, 0].set_xlabel('Alpha [°]')
axes[1, 0].set_ylabel('CM [-]')
axes[1, 0].set_title('Moment')
axes[1, 0].axhline(y=0, color='k')
axes[1, 0].axvline(x=0, color='k')
axes[1, 0].legend()
axes[1, 0].grid()

axes[1, 1].plot(dfltt['CL'], dfltt['CL']/dfltt['CD'], label="LTT", marker='.', color='blue')
axes[1, 1].plot(dfpanels['CL'], dfpanels['CL']/dfpanels['CD'], label="Panels", marker='.', color='red')
axes[1, 1].plot(dfvlm2['CL'], dfvlm2['CL']/dfvlm2['CD'], label="VLM2", marker='.', color='yellow')
axes[1, 1].plot(df3d['CL'][:33], df3d['CL'][:33]/df3d['CD'][:33], label="Windtunnel", marker='.', color='green')
axes[1, 1].set_xlabel('CL[-]')
axes[1, 1].set_ylabel('CL/CD [-]')
axes[1, 1].set_title('L/D vs CL')
axes[1, 1].axhline(y=0, color='k')
axes[1, 1].axvline(x=0, color='k')
axes[1, 1].legend()
axes[1, 1].grid()

axes[1, 2].plot(dfltt['alpha'], dfltt['CL']/dfltt['CD'], label="LTT", marker='.', color='blue')
axes[1, 2].plot(dfpanels['alpha'], dfpanels['CL']/dfpanels['CD'], label="Panels", marker='.', color='red')
axes[1, 2].plot(dfvlm2['alpha'], dfvlm2['CL']/dfvlm2['CD'], label="VLM2", marker='.', color='yellow')
axes[1, 2].plot(df3d['Alpha'][:33], df3d['CL'][:33]/df3d['CD'][:33], label="Windtunnel", marker='.', color='green')
axes[1, 2].set_xlabel('Alpha [°]')
axes[1, 2].set_ylabel('CL/CD [-]')
axes[1, 2].set_title('L/D vs Alpha')
axes[1, 2].axhline(y=0, color='k')
axes[1, 2].axvline(x=0, color='k')
axes[1, 2].legend()
axes[1, 2].grid()

plt.show()