from dataframes import df2d, dfxfoil
import pandas as pd
from matplotlib import pyplot as plt


fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(20, 12))
plt.tight_layout(pad=5)
plt.suptitle(f'XFOIL vs Windtunnel (2D)', size=15)

axes[0, 0].plot(dfxfoil['alpha'], dfxfoil['CL'], label="Xfoil", marker='.', color='blue')
axes[0, 0].plot(df2d['Alpha'][:33], df2d['Cl'][:33], label="Windtunnel", marker='.', color='red')
axes[0, 0].set_xlabel('Alpha [°]')
axes[0, 0].set_ylabel('Cl [-]')
axes[0, 0].set_title('Lift Slope')
axes[0, 0].axhline(y=0, color='k')
axes[0, 0].axvline(x=0, color='k')
axes[0, 0].legend()
axes[0, 0].grid()

axes[0, 1].plot(dfxfoil['alpha'], dfxfoil['CD'], label="Xfoil", marker='.', color='blue')
axes[0, 1].plot(df2d['Alpha'][:33], df2d['Cd'][:33], label="Windtunnel", marker='.', color='red')
axes[0, 1].set_xlabel('Alpha [°]')
axes[0, 1].set_ylabel('Cd [-]')
axes[0, 1].set_title('Drag Slope')
axes[0, 1].axhline(y=0, color='k')
axes[0, 1].axvline(x=0, color='k')
axes[0, 1].legend()
axes[0, 1].grid()

axes[0, 2].plot(dfxfoil['CD'], dfxfoil['CL'], label="Xfoil", marker='.', color='blue')
axes[0, 2].plot(df2d['Cd'][:33], df2d['Cl'][:33], label="Windtunnel", marker='.', color='red')
axes[0, 2].set_xlabel('Alpha [°]')
axes[0, 2].set_ylabel('Cl [-]')
axes[0, 2].set_title('Drag Bucket')
axes[0, 2].axhline(y=0, color='k')
axes[0, 2].axvline(x=0, color='k')
axes[0, 2].legend()
axes[0, 2].grid()

axes[1, 0].plot(dfxfoil['alpha'], dfxfoil['Cm'], label="Xfoil", marker='.', color='blue')
axes[1, 0].plot(df2d['Alpha'][:33], df2d['Cm'][:33], label="Windtunnel", marker='.', color='red')
axes[1, 0].set_xlabel('Alpha [°]')
axes[1, 0].set_ylabel('Cm [-]')
axes[1, 0].set_title('Moment')
axes[1, 0].axhline(y=0, color='k')
axes[1, 0].axvline(x=0, color='k')
axes[1, 0].legend()
axes[1, 0].grid()

axes[1, 1].plot(dfxfoil['alpha'], dfxfoil['CL']/dfxfoil['CD'], label="Xfoil", marker='.', color='blue')
axes[1, 1].plot(df2d['Alpha'][:33], df2d['Cd'][:33], label="Windtunnel", marker='.', color='red')
axes[1, 1].set_xlabel('Alpha [°]')
axes[1, 1].set_ylabel('Cd [-]')
axes[1, 1].set_title('Drag Slope')
axes[1, 1].axhline(y=0, color='k')
axes[1, 1].axvline(x=0, color='k')
axes[1, 1].legend()
axes[1, 1].grid()

axes[1, 2].plot(dfxfoil['CD'], dfxfoil['CL'], label="Xfoil", marker='.', color='blue')
axes[1, 2].plot(df2d['Cd'][:33], df2d['Cl'][:33], label="Windtunnel", marker='.', color='red')
axes[1, 2].set_xlabel('Alpha [°]')
axes[1, 2].set_ylabel('Cl [-]')
axes[1, 2].set_title('Drag Bucket')
axes[1, 2].axhline(y=0, color='k')
axes[1, 2].axvline(x=0, color='k')
axes[1, 2].legend()
axes[1, 2].grid()

plt.show()